### ISSUE TITLE
hey how to use this please make a video

### ISSUE THREAD

**Issue by gitgraber23** [gwen001/keyhacks#1]

**Comment by gwen001** [comment]
My pinky is telling me you're the kind of person who puts the whole email content in the subject, but I may be wrong of course...

If you find the answer to your question by yourself, I'll by you this tee-shirt.
<img width="786" alt="Screenshot 2023-05-14 at 12 51 45" src="https://github.com/gwen001/keyhacks.sh/assets/5347721/1338769f-6719-408d-9e5e-4e8bc1ccbb3a">
